<#
    lint-door-coverage.ps1 -- section 11.9's machine check for DOOR COVERAGE.

    Called by verify.bat, inside step [1/6], before the Release build.  Exit code
    IS the verdict:

        0  every candidate the predicate generated has a home
        1  at least one candidate is neither guarded nor archived  -> gate RED
        3  this script could not parse something, or threw          -> gate RED

    verify.bat treats anything that is not 0 as red.  Same contract as
    tools\classify-asan.ps1, and for the same reason: a checker that fails open
    is worse than no checker, because it looks like one.

    ----------------------------------------------------------------------------
    WHY THIS EXISTS
    ----------------------------------------------------------------------------
    Six recurrences of the same defect family, and every one of them was found by
    a person re-reading code that a person had already reviewed.  E19 wrote the
    sentence this file is the answer to:

        layoutRect() was found by a HUMAN, not by a machine -- which is exactly
        why that lint has to exist, and evidence that it does not yet.

    Section 11.2's static_assert checks a TYPE SHAPE.  deathWatchDepth() checks
    that a list balances.  Neither of them, nor anything else in this tree, can
    say "the ninth door was written without a guard".  That is what is here.

    ----------------------------------------------------------------------------
    THE FOUR PROPERTIES (section 11.9; NOT negotiable, do not relax)
    ----------------------------------------------------------------------------
    1. THE CANDIDATE SET IS GENERATED BY A PREDICATE, not by a list of names
       somebody typed.  Below: split each translation unit into function bodies,
       find the door primitives in each, and emit a candidate for every body that
       has a door which is not its last statement and has no DeathWatch in it.
       Over-reporting is allowed and expected; under-reporting is the defect
       family itself.

    2. EVERY CANDIDATE MUST HAVE A HOME: guarded, or present in the allowlist
       WITH a reason, a grade (S1/S2/S3) and a round (W1/W2/W3).

    3. AN UNARCHIVED CANDIDATE MAKES verify.bat RED.  That is the detection point
       for "the ninth door was written and nobody noticed".

    4. THE P1 HALF OF THE CANDIDATE SET IS GENERATED FROM THE DECLARATION SIDE.
       This one is load bearing and it is the reason the first cut of this scan
       (a grep for a hand-written list of call-site names) missed layoutRect()
       for two rounds: A VIRTUAL CALL HAS NO NAME TO GREP.  Whether `c->foo()`
       is a door depends on whether `foo` is declared virtual in a HEADER, not
       on anything visible at the call site.  So: collect every virtual member
       function name from include\geeyoou\**\*.hpp, and use THAT generated list.

       AND THE SCAN ROOT IS THE WHOLE OF include\geeyoou, not Widget.hpp.  That
       is a SECOND hole, not the same one: Layout::onInvalidated /
       onChildAppended / onChildRemoved were missed because the SUBJECT was
       written too narrowly ("any virtual of a widget"), and declaration-side
       generation rooted at Widget.hpp would still miss all three.  Two holes,
       two fixes, and closing one does not close the other.

       AND THAT ROOT IS THE CANDIDATE SIDE'S TOO -- the same hole, a THIRD time,
       and it stood for three rounds after the other two were closed.  The two
       fixes above were both applied on the DECLARATION side; the CANDIDATE side
       kept scanning `src\**\*.cpp`, and this library's code is not all in src.
       A template in a header is a function body like any other, and two of them
       were doors with writes after them: AppWindow::setContent and
       WindowHeader::addTrailingItem.  Whoever narrows a scan root next: the
       question is never "where are the .cpp files", it is "where is the code".

       (Two mechanical traps came with it, both measured, both recorded at their
       fix: -Include does nothing next to -LiteralPath -Recurse, and `template`
       is in NotAFunctionHead so every template body read as "not a function".
       Widening the root without the second fix buys exactly nothing.)

    ----------------------------------------------------------------------------
    THE ALLOWLIST AND THE P2 LIST ARE SECTION 11.4'S.  THERE IS NO SECOND COPY.
    ----------------------------------------------------------------------------
    This script parses docs\iterations\02-layout-engine.md section 11.4 and takes
    its tables as the register of archived candidates, AND its P2 clause as the
    list of library primitives that reach application code.  Writing either out a
    second time here would be the mistake Widget.cpp:74-75 already names: the
    second hand-copy is the second place that gets forgotten -- and the P2 copy
    HAD already drifted (the script had `relayout`, the document did not) with a
    comment above it saying "when you add one here, add it there too".

    THE KEY IS (FILE, FUNCTION), NOT (FILE, LINE).  The table's own words:
    "the statement is what the table is about, the line number is not" -- line
    numbers in that table were already stale by a hundred lines after E14, and a
    lint keyed on them would redden on every unrelated edit, which is the
    always-on red light section 11.9 rejected the runtime counter for being.

    ----------------------------------------------------------------------------
    FAIL-CLOSED, EVERYWHERE
    ----------------------------------------------------------------------------
      * a function body this script cannot delimit        -> reported, red
      * a table row with no grade or no round             -> NOT archived
      * a table row naming a file but no function         -> NOT archived
      * a doc with no parseable section 11.4              -> exit 3, red
      * a source file that cannot be read                 -> exit 3, red

    A false red costs somebody an hour.  A false green costs a use-after-free in
    a release, and all six in this family were green on two of the three legs.

    ----------------------------------------------------------------------------
    WHAT THIS DELIBERATELY DOES NOT DO
    ----------------------------------------------------------------------------
      * It does not decide DANGER.  Section 11.4's hazard clause ("the door is
        dangerous to P iff something after it reaches through P") needs to know
        what a name refers to, which needs a compiler.  This script answers the
        cheaper question -- is there a door with code after it and no cursor --
        and makes a HUMAN answer the expensive one, in the table, on the record.
      * It does not tell HOLDING a cursor from CHECKING one.  Section 11.9 says
        "no DeathWatch in the body"; this file reads that as "no REM3 cursor in
        the body", because all four of them (DeathWatch, BubbleGuard,
        GeometryGuard, LayoutGuard) are the same LiveGuard mechanism and the
        literal reading filed Widget::dispatchMouse and dispatchKey as defects
        while both of them re-test their cursor after the door.  The widening is
        argued where it is implemented ($CursorGuardPattern) and the residue it
        leaves is registered in section 12.4 rather than glossed over.
      * It does not scan tests\ or examples\.  Section 11.4 row #25 registers the
        examples exposure separately and R3 does not change examples.
#>

[CmdletBinding()]
param(
    # Repository root.  Defaults to this script's parent.
    [string] $RepoRoot = '',

    # The design document holding section 11.4.  Defaults to the real one under
    # $RepoRoot; exists as a parameter only so the self-test can point it at a
    # fixture, and so that the "delete one row and watch it redden" proof can be
    # run WITHOUT editing the real document.
    [string] $DocPath = '',

    # Print verdict lines only.
    [switch] $Quiet,

    # How many unarchived candidates to print before folding the rest into a
    # count.  The gate wants a readable failure, not a wall; a person triaging
    # the first scan wants all of them.  Capping the DISPLAY only -- the verdict
    # is always computed from every candidate.
    [int] $MaxList = 40,

    # Load the functions and return without linting anything and without
    # exiting.  Only tools\test-lint-door-coverage.ps1 uses this, so that the
    # self-test can run its whole table in ONE powershell process -- see the
    # budget note in that file.
    [switch] $DefineOnly,

    # Run ONLY Test-GateStillCallsItsCheckers and exit 0/1.
    #
    # ⚠ THIS EXISTS TO BREAK A SELF-REFERENCE, and the self-reference is the
    # whole reason the wiring check was worth writing.  This lint is invoked by
    # verify.bat's :lint_doors, so it CANNOT catch the deletion of `call
    # :lint_doors` -- it is not running.  It catches the deletion of `call
    # :classify_asan`; the other direction has to be checked by something that
    # still runs, which is the ASan leg.  So tools\test-classify-asan.ps1
    # spawns this switch, and the two checkers watch each other's power cord.
    #
    # A SPAWN AND NOT A DOT-SOURCE, deliberately: both scripts keep their own
    # $script:Emitted and their own Write-* helper, and dot-sourcing one into
    # the other silently shares them.  0.6s of cold start is a cheap price for
    # the two files not being able to break each other by accident.
    [switch] $GateWiringOnly
)

Set-StrictMode -Version 1.0
$ErrorActionPreference = 'Stop'

$EXIT_COVERED   = 0
$EXIT_UNCOVERED = 1
$EXIT_INTERNAL  = 3

# Captured at load time: when this file is dot-sourced, $PSScriptRoot inside a
# function called later resolves against the CALLER's script, not this one.
$script:LintDir = $PSScriptRoot

$script:Emitted = New-Object System.Collections.ArrayList
$script:Silent  = $false
function Write-LintLine {
    param([string] $Text = '')
    [void] $script:Emitted.Add($Text)
    if (-not $script:Silent) { [Console]::Out.WriteLine($Text) }
}

# ---------------------------------------------------------------------------
# Blank out comments and string / character literals, PRESERVING LENGTH and
# every newline, so that every offset computed afterwards still maps to the
# original line number.
#
# This is not a nicety in this repository.  The comments here are longer than
# the code and they QUOTE THE DOOR NAMES: Window.cpp's header says
# "onFocusChanged is a protected virtual: a P1 door", AppWindow.cpp's says
# "header_->setGeometry".  Scanning raw text would report a door in a comment
# that exists to explain a door, which is a special kind of useless.
# ---------------------------------------------------------------------------
function Clear-CppNoise {
    param([string] $Text)

    $out = New-Object System.Text.StringBuilder
    $n = $Text.Length
    $i = 0
    while ($i -lt $n) {
        $c = $Text[$i]
        $d = ''
        if ($i + 1 -lt $n) { $d = $Text[$i + 1] }

        if ($c -eq '/' -and $d -eq '/') {
            while ($i -lt $n -and $Text[$i] -ne "`n") {
                if ($Text[$i] -eq "`r") { [void] $out.Append("`r") } else { [void] $out.Append(' ') }
                $i++
            }
            continue
        }
        if ($c -eq '/' -and $d -eq '*') {
            [void] $out.Append('  '); $i += 2
            while ($i -lt $n) {
                if ($Text[$i] -eq '*' -and $i + 1 -lt $n -and $Text[$i + 1] -eq '/') {
                    [void] $out.Append('  '); $i += 2; break
                }
                if ($Text[$i] -eq "`n") { [void] $out.Append("`n") }
                elseif ($Text[$i] -eq "`r") { [void] $out.Append("`r") }
                else { [void] $out.Append(' ') }
                $i++
            }
            continue
        }
        if ($c -eq '"' -or $c -eq "'") {
            $quote = $c
            [void] $out.Append(' '); $i++
            while ($i -lt $n) {
                if ($Text[$i] -eq '\') {
                    [void] $out.Append('  ')
                    $i += 2
                    continue
                }
                if ($Text[$i] -eq $quote) { [void] $out.Append(' '); $i++; break }
                if ($Text[$i] -eq "`n") { [void] $out.Append("`n") }
                elseif ($Text[$i] -eq "`r") { [void] $out.Append("`r") }
                else { [void] $out.Append(' ') }
                $i++
            }
            continue
        }

        [void] $out.Append($c)
        $i++
    }
    return $out.ToString()
}

# Comment-stripping the same file twice is pure waste, and this script used to
# do exactly that: once to collect virtual names or door candidates, and once
# more for the Platform install-point predicate.  Keyed on path AND last-write
# time, so a fixture the self-test rewrites between cases is never served stale.
$script:CleanCache = @{}
function Get-CleanText {
    param([string] $Path)
    $stamp = [System.IO.File]::GetLastWriteTimeUtc($Path).Ticks
    $key = $Path + '|' + $stamp
    if ($script:CleanCache.ContainsKey($key)) { return $script:CleanCache[$key] }
    $v = Clear-CppNoise ([System.IO.File]::ReadAllText($Path))
    $script:CleanCache[$key] = $v
    return $v
}

# Every translation-unit-shaped file under a scan root.
#
# ⚠ NOT `Get-ChildItem -LiteralPath ... -Recurse -Include *.cpp`, which is what
# this script used and which DOES NOT FILTER.  Measured on this machine,
# PowerShell 5.1.19041:
#
#     Get-ChildItem -LiteralPath <include> -Recurse -File -Include *.cpp  -> 59
#     Get-ChildItem -Path        <include> -Recurse -File -Include *.cpp  ->  0
#
# -Include is matched against the LiteralPath and silently ignored for the
# recursion, so the "only .cpp" in the old scan was not a filter at all -- it
# was `src` happening to contain almost nothing else.  It contains one thing
# else (src\render\VectorPathImpl.hpp), which was therefore being scanned by
# accident, and the day somebody drops a .md or a .natvis in there it would
# have been read as C++ and reported as an unbalanced body.  A filter that does
# not filter is the same defect as a lint that does not lint.
#
# -Filter is not the fix either: the FileSystem provider's wildcard still
# carries 8.3 semantics, so `*.cpp` matches `foo.cppm`.  The extension is
# tested directly instead; this tree is 106 files and the walk is not the cost.
function Get-SourceFiles {
    param([string] $Dir)
    return @(Get-ChildItem -LiteralPath $Dir -Recurse -File |
             Where-Object { $_.Extension -eq '.cpp' -or $_.Extension -eq '.hpp' } |
             Sort-Object FullName)
}

# Offset -> 1-based line number.  Built once per file.
function New-LineIndex {
    param([string] $Text)
    $starts = New-Object System.Collections.ArrayList
    [void] $starts.Add(0)
    for ($i = 0; $i -lt $Text.Length; $i++) {
        if ($Text[$i] -eq "`n") { [void] $starts.Add($i + 1) }
    }
    return $starts
}
function Get-LineOf {
    param($LineStarts, [int] $Offset)
    $lo = 0; $hi = $LineStarts.Count - 1
    while ($lo -lt $hi) {
        $mid = [int](($lo + $hi + 1) / 2)
        if ($LineStarts[$mid] -le $Offset) { $lo = $mid } else { $hi = $mid - 1 }
    }
    return $lo + 1
}

# ---------------------------------------------------------------------------
# THE P1 INPUT: every virtual member function name declared anywhere under
# include\geeyoou.  Property 4.  Destructors are excluded -- a destructor is not
# a door in this family's sense; it is the thing the doors are dangerous
# BECAUSE of.
#
# `override` declarations are collected too: a subclass override is a virtual
# whether or not the word `virtual` is repeated, and SelectBase.hpp writes them
# both ways.
# ---------------------------------------------------------------------------
function Get-VirtualNames {
    param([string[]] $HeaderPaths)

    $names = @{}
    foreach ($p in $HeaderPaths) {
        $clean = Get-CleanText $p
        foreach ($line in ($clean -split "`r`n|`n|`r")) {
            $isVirtual  = ($line -match '(^|[^\w])virtual\s')
            $isOverride = ($line -match '\)\s*(const\s*)?(noexcept\s*)?override\b')
            if (-not $isVirtual -and -not $isOverride) { continue }
            # The declared name is the identifier in front of the first
            # parameter list on the line.
            $m = [regex]::Match($line, '(?<tilde>~\s*)?(?<name>[A-Za-z_]\w*)\s*\(')
            if (-not $m.Success) { continue }
            # NOT just `virtual ~`.  Half of this tree writes its destructor as
            # `~Foo() override;` with no `virtual` on the line at all, and a
            # `virtual ~`-only filter let five of them through as if `AppWindow`,
            # `Widget`, `Window`, `MenuButton` and `SelectBase` were door names --
            # which then matched every `new Widget(` in the library.
            if ($m.Groups['tilde'].Success) { continue }
            $nm = $m.Groups['name'].Value
            if ($nm -in @('if', 'for', 'while', 'switch', 'return', 'sizeof', 'catch')) { continue }
            if (-not $names.ContainsKey($nm)) { $names[$nm] = New-Object System.Collections.ArrayList }
            $leaf = Split-Path -Leaf $p
            if (-not $names[$nm].Contains($leaf)) { [void] $names[$nm].Add($leaf) }
        }
    }
    return $names
}

# Section 11.4's "looked at it, does not need shutting" list exempts the 21
# non-destructor virtuals of platform\Platform.hpp, and the reason is
# STRUCTURAL rather than a usage observation: Platform& platform() is the only
# way in the library to obtain an implementation, and there is no setter, no
# registration point and no factory, so those virtuals cannot be overridden by
# an application -- there is no interface to do it through.
#
# Applied here, and applied MECHANICALLY, because the alternative is a name
# collision that makes the lint stupid: PlatformWindow declares restore(),
# show(), invalidate(), close() and thirteen more, and leaving them in the P1
# set makes every painter.restore() and every Layout::invalidate() look like a
# door.  A name that is ALSO declared outside Platform.hpp stays in -- close()
# is a SelectBase virtual as well, and that one is a genuine door.
#
# THE EXEMPTION IS GATED, NOT ASSUMED: Test-NoPlatformInstallPoint runs on every
# invocation and reddens the gate the day an install point appears, at which
# point these names come back and get graded one by one.  That gate is the whole
# reason this is allowed to be a subtraction.
function Remove-PlatformOnlyNames {
    param([hashtable] $Names)
    $out = @{}
    foreach ($k in $Names.Keys) {
        $headers = @($Names[$k])
        $nonPlatform = @($headers | Where-Object { $_ -ne 'Platform.hpp' })
        if ($nonPlatform.Count -eq 0) { continue }
        $out[$k] = $Names[$k]
    }
    return $out
}

# ---------------------------------------------------------------------------
# Approximate function-body splitting: brace balance plus a header test.  Not a
# parser, and section 11.9 says so up front.  What it must never do is MISS a
# body, because a missed body is a missed candidate; over-splitting only costs
# noise.
# ---------------------------------------------------------------------------
$script:NotAFunctionHead = '^(if|for|while|switch|catch|do|else|return|namespace|class|struct|union|enum|extern|template|using|typedef|public|private|protected)\b'

function Test-FunctionHeader {
    param([string] $Snippet)

    $s = $Snippet.Trim()
    if (-not $s) { return $null }

    # A `template <...>` prefix, STRIPPED BEFORE the NotAFunctionHead test.
    #
    # This is the second half of the candidate-side scan-root hole, and without
    # it widening the root buys nothing.  `template` is in NotAFunctionHead, so
    # every template body read as "not a function": the splitter descended into
    # it looking for functions INSIDE, found none, and the whole body -- doors
    # and all -- was never scanned.  Measured on AppWindow.hpp: the splitter
    # reported header/content/isBorderVisible and NOT setContent, whose body is
    # `add<T>()` (a P2 door) followed by two writes through `this`.
    #
    # Brace-counting the angle brackets rather than a lazy `.*?>`: `template
    # <class T, std::vector<int> V>` has a nested pair, and the lazy form stops
    # at the first `>` and leaves `V>` in front of the name.
    while ($s -match '^template\s*<') {
        $k = $s.IndexOf('<')
        $d = 0
        $end = -1
        for ($q = $k; $q -lt $s.Length; $q++) {
            if ($s[$q] -eq '<') { $d++ }
            elseif ($s[$q] -eq '>') { $d--; if ($d -eq 0) { $end = $q; break } }
        }
        if ($end -lt 0) { return $null }
        $s = $s.Substring($end + 1).Trim()
        if (-not $s) { return $null }
    }

    # `} else {`, `namespace detail {`, `class Foo : public Bar {` ...
    if ($s -match $script:NotAFunctionHead) { return $null }
    # An initialiser, not a definition.  `==` / `!=` / `<=` / `>=` are not
    # assignments, and `= default` / `= delete` / `= 0` never precede a body.
    $noCmp = [regex]::Replace($s, '[=!<>]=', '@@')
    if ($noCmp -match '=') { return $null }
    # A lambda body, a designated initialiser, an array of structs.
    if ($s -match '\]\s*(\([^)]*\))?\s*(mutable)?\s*(->[^{]*)?$' -and $s -match '\[') { return $null }

    $open = $s.IndexOf('(')
    if ($open -lt 0) { return $null }
    $head = $s.Substring(0, $open)
    $m = [regex]::Match($head, '(?<q>[A-Za-z_]\w*(\s*::\s*[A-Za-z_]\w*)*)\s*$')
    if (-not $m.Success) { return $null }

    $qual = [regex]::Replace($m.Groups['q'].Value, '\s+', '')
    $name = $qual
    $k = $qual.LastIndexOf('::')
    if ($k -ge 0) { $name = $qual.Substring($k + 2) }
    if (-not $name) { return $null }
    if ($name -match $script:NotAFunctionHead) { return $null }
    return @{ Name = $name; Qualified = $qual }
}

function Split-CppFunctions {
    param([string] $Clean)

    $funcs = New-Object System.Collections.ArrayList
    $n = $Clean.Length
    # Offset just past the last `;`, `{` or `}` seen at the current point --
    # i.e. where the snippet in front of the next `{` starts.
    $snippetStart = 0
    $i = 0
    # Stack of open braces we have descended into WITHOUT calling them a
    # function (namespaces, classes, structs, initialiser lists).
    $depth = 0

    while ($i -lt $n) {
        $c = $Clean[$i]
        if ($c -eq ';' -or $c -eq '}') { $snippetStart = $i + 1; $i++; continue }
        if ($c -ne '{') { $i++; continue }

        $snippet = $Clean.Substring($snippetStart, $i - $snippetStart)
        $hdr = Test-FunctionHeader $snippet

        if ($null -eq $hdr) {
            # Not a function: descend, keep looking inside (a class body in a
            # .cpp holds member function definitions, and Widget.cpp has three).
            $snippetStart = $i + 1
            $depth++
            $i++
            continue
        }

        # A function.  Find its matching close brace, record the body, and
        # resume AFTER it -- we do not look for functions inside a function.
        $d = 0
        $j = $i
        while ($j -lt $n) {
            if ($Clean[$j] -eq '{') { $d++ }
            elseif ($Clean[$j] -eq '}') {
                $d--
                if ($d -eq 0) { break }
            }
            $j++
        }
        if ($j -ge $n) {
            # Unbalanced.  Fail closed: report it and stop scanning this file.
            [void] $funcs.Add(@{
                Name = $hdr.Name; Qualified = $hdr.Qualified
                HeadOffset = $snippetStart; BodyStart = $i + 1; BodyEnd = $n
                Unbalanced = $true
            })
            break
        }

        [void] $funcs.Add(@{
            Name = $hdr.Name; Qualified = $hdr.Qualified
            HeadOffset = $snippetStart; BodyStart = $i + 1; BodyEnd = $j
            Unbalanced = $false
        })
        $i = $j + 1
        $snippetStart = $i
    }
    return $funcs
}

# ---------------------------------------------------------------------------
# The P2 door primitives.  PARSED FROM SECTION 11.4, NOT WRITTEN HERE.
#
# This used to be a literal array with a comment saying "when you add one here,
# add it there too", and by the time the fourth security review read it the two
# copies had already drifted: `relayout` was in the script and not in the
# document.  That drift happened to be in the RED direction, which is the only
# reason nothing was missed -- the same accident the other way deletes a whole
# class of candidate and turns the gate green while doing it.
#
# Section 11.9 property 2 already settled this for the allowlist -- "allowlist
# 就是 §11.4 的表，两者不得各写一份" -- and the P2 list is the same kind of
# object: a register a human maintains and a machine consumes.  So it obeys the
# same rule, and Widget.cpp:74-75's rule with it: the second hand-copy is the
# second place that gets forgotten.
#
# Filled in by Invoke-LintDoorCoverage from the document under test.  Empty here
# on purpose: an empty list builds the never-matching pattern in New-DoorMatcher
# rather than an all-matching one, so a code path that somehow skipped the parse
# under-reports loudly instead of matching every parenthesis in the tree.
# ---------------------------------------------------------------------------
$script:P2Names = @()

# The P2 clause of section 11.4, reduced to bare identifiers.
#
# The clause is prose a person reads, so the reduction is spelled out and it is
# STRICT: `add<T>` -> add, `Window::openPopup` -> openPopup.  A backticked token
# on that line that does not reduce to an identifier is exit 3, not a skip.  A
# skip would mean a typo in the document silently drops a primitive, and a
# dropped primitive is a silently deleted class of candidate -- the failure this
# whole parse exists to prevent.  Keep prose references out of backticks on that
# one line.
function Read-DoorPrimitivesP2 {
    param([string] $DocPath)

    $result = @{ Names = @(); Error = '' }

    if (-not (Test-Path -LiteralPath $DocPath)) {
        $result.Error = 'design document not found: ' + $DocPath
        return $result
    }

    $lines = [System.IO.File]::ReadAllLines($DocPath, [System.Text.Encoding]::UTF8)
    $inSection = $false
    $clause = $null
    foreach ($line in $lines) {
        if ($line -match '^###\s+11\.4(\s|$)')  { $inSection = $true;  continue }
        if ($inSection -and $line -match '^###\s+11\.5(\s|$)') { break }
        if (-not $inSection) { continue }
        if ($line -match '\*\*P2\*\*') { $clause = $line; break }
    }
    if ($null -eq $clause) {
        $result.Error = 'no P2 primitive clause in section 11.4 of ' + $DocPath
        return $result
    }

    $names = @()
    foreach ($m in [regex]::Matches($clause, '`([^`]+)`')) {
        $tok = $m.Groups[1].Value
        $t = [regex]::Replace($tok, '<[^<>]*>', '')
        $k = $t.LastIndexOf('::')
        if ($k -ge 0) { $t = $t.Substring($k + 2) }
        $t = $t.Trim()
        if ($t -notmatch '^[A-Za-z_]\w*$') {
            $result.Error = 'the P2 clause of section 11.4 has a backticked token this script ' +
                            'cannot reduce to one identifier: `' + $tok + '`'
            return $result
        }
        if (-not ($names -contains $t)) { $names += $t }
    }
    if ($names.Count -eq 0) {
        $result.Error = 'the P2 clause of section 11.4 names no primitives'
        return $result
    }

    $result.Names = $names
    return $result
}

# ONE compiled alternation per primitive class, not one regex per name.
#
# Not a micro-optimisation: with 38 virtual names and 15 P2 names, per-name
# scanning is 53 passes over every function body in the tree, and it measured
# 14.9 SECONDS on this repository.  The gate runs this, and the self-test runs
# it twice more; a check that adds three quarters of a minute to every build is
# a check somebody deletes.  Folded into three passes it is under a second.
#
# `(?<!::)` rather than capturing the two preceding characters: a QUALIFIED call
# is statically bound and is not a P1 door (section 11.4), and a lookbehind
# expresses that without consuming input -- which matters, because a consuming
# prefix makes two adjacent calls overlap and silently drops the second.  A
# dropped door is an under-report, and under-reporting is the defect family.
function New-DoorMatcher {
    param([hashtable] $VirtualNames)

    $opt = [System.Text.RegularExpressions.RegexOptions]::Compiled
    # `(?!)` is the never-matching pattern.  It is here because the alternative
    # is far worse than it looks: an EMPTY name list builds `(?<n>)`, an empty
    # alternation, and `(?<!::)\b(?<n>)\s*\(` then matches EVERY parenthesis in
    # the tree with an empty door name.  Caught by the Platform-exemption
    # fixture, where the exemption legitimately empties the P1 set, and it
    # produced `first: P1 ` with nothing after it -- output that is not merely
    # over-red but meaningless, which is how a gate stops being read.
    $never = '(?!)'

    $p1 = $never
    if ($VirtualNames.Count -gt 0) {
        $p1 = '(?<!::)\b(?<n>' +
              (($VirtualNames.Keys | Sort-Object | ForEach-Object { [regex]::Escape($_) }) -join '|') +
              ')\s*\('
    }
    # ⚠ P2 CARRIES NO `(?<!::)`, AND P1 DOES.  The lookbehind's warrant is
    # section 11.4's sentence "a qualified call is not P1", and that sentence is
    # about VIRTUAL DISPATCH: `PushButton::sizeHint()` is statically bound, so it
    # cannot land in an application override.  P2 is not dispatch.  P2 is a list
    # of library functions known to reach application code, and
    # `Widget::setGeometry(r)` or `Base::relayout()` reaches it just as well
    # written qualified -- the qualification picks the implementation, it does
    # not stop the implementation running an application's onGeometryChanged.
    #
    # Copying the lookbehind onto P2 was therefore a category error, and the
    # direction it errs in is UNDER-REPORTING, which is this defect family
    # itself.  It is not a live defect today -- every qualified call in the tree
    # is a P1-family name -- which is exactly why it had to be fixed on the
    # argument rather than on a red light.
    $p2 = $never
    if ($script:P2Names.Count -gt 0) {
        $p2 = '\b(?<n>' +
              (($script:P2Names | Sort-Object | ForEach-Object { [regex]::Escape($_) }) -join '|') +
              ')\s*[<(]'
    }

    return @{
        P1 = New-Object System.Text.RegularExpressions.Regex($p1, $opt)
        P2 = New-Object System.Text.RegularExpressions.Regex($p2, $opt)
        P3 = New-Object System.Text.RegularExpressions.Regex('(\.|->)emit\s*\(', $opt)
    }
}

function Find-Doors {
    param([string] $Body, [hashtable] $Matcher)

    $doors = New-Object System.Collections.ArrayList

    # P1 -- generated from the declaration side.  `x->foo()`, `x.foo()` and a
    # bare `foo()` are all dispatch; `Base::foo()` is not.
    foreach ($m in $Matcher.P1.Matches($Body)) {
        [void] $doors.Add(@{ Kind = 'P1'; Name = $m.Groups['n'].Value; Offset = $m.Index })
    }
    # P2 -- named library functions known to reach application code.
    foreach ($m in $Matcher.P2.Matches($Body)) {
        [void] $doors.Add(@{ Kind = 'P2'; Name = $m.Groups['n'].Value; Offset = $m.Index })
    }
    # P3 -- signal emission.
    foreach ($m in $Matcher.P3.Matches($Body)) {
        [void] $doors.Add(@{ Kind = 'P3'; Name = 'emit'; Offset = $m.Index })
    }

    return ($doors | Sort-Object { $_.Offset })
}

# ---------------------------------------------------------------------------
# WHAT COUNTS AS A CURSOR ON THIS FRAME.
#
# Section 11.9 says "no DeathWatch in the body", and the first cut of this file
# took that literally because the literal reading is the redder one.  It was
# WRONG, and measurably so, not as a matter of taste: it reported
# Widget::dispatchMouse and Widget::dispatchKey as unguarded, and both of them
# carry a BubbleGuard AND re-test it after the door --
#
#     w->onMouse(local);              <- the door
#     if (local.accepted) { ... }
#     if (bubble.node() != w) return; <- the check
#
# -- which is the very shape REM3-G2/G3 ask for, written before REM3 existed.
# A lint that files a correct frame as a defect is how a lint gets muted, and a
# muted lint is the failure mode section 11.9 rejected the runtime counter for.
#
# So the predicate is "the frame holds a REM3 CURSOR", and all four of them are
# the same mechanism: LiveGuard<List> over a list that ~Widget cancels.
# DeathWatch was simply the only one in scope when 11.9 was written.
#
# ⚠ REGISTERED RESIDUE, because this is a WIDENING and widenings are how this
# family recurs: holding a cursor is not the same as CHECKING it, and this test
# cannot tell the two apart.  A frame that constructs a LayoutGuard for its own
# reasons and then walks through a door without asking alive() reads as guarded
# here.  Closing that needs the check to be tied to the door, which needs to
# know which pointer the door is dangerous to -- section 11.4's hazard clause,
# i.e. a compiler.  Recorded in section 12.4 rather than pretended away.
$script:CursorGuardPattern = '\b(DeathWatch|BubbleGuard|GeometryGuard|LayoutGuard)\b'

# Is there any code after this door's own statement, other than the closing
# brace?  "The door is the last statement" is section 11.9's one exclusion, and
# ScrollArea.cpp:165 / :174 and Widget.cpp:548 are the rows it exists for.
function Test-CodeFollowsDoor {
    param([string] $Body, [int] $DoorOffset)

    $depth = 0
    $i = $DoorOffset
    $n = $Body.Length
    while ($i -lt $n) {
        $c = $Body[$i]
        if ($c -eq '(' -or $c -eq '[' -or $c -eq '{') { $depth++ }
        elseif ($c -eq ')' -or $c -eq ']' -or $c -eq '}') {
            $depth--
            # Ran off the end of the body without a `;`: the door was the last
            # expression, e.g. `return layout_->measureFor(...)` has its `;`
            # first, so this only happens on malformed input.  Fail closed.
            if ($depth -lt 0) { return $true }
        }
        elseif ($c -eq ';' -and $depth -eq 0) { break }
        $i++
    }
    if ($i -ge $n) { return $true }
    $tail = $Body.Substring($i + 1)
    $tail = [regex]::Replace($tail, '[\s}]', '')
    return ($tail.Length -gt 0)
}

# ---------------------------------------------------------------------------
# THE ALLOWLIST: section 11.4 of the design document.  Parsed, never copied.
# ---------------------------------------------------------------------------
function Read-DoorAllowlist {
    param([string] $DocPath)

    $result = @{ Keys = @{}; Rows = 0; Error = '' }

    if (-not (Test-Path -LiteralPath $DocPath)) {
        $result.Error = 'design document not found: ' + $DocPath
        return $result
    }

    $lines = [System.IO.File]::ReadAllLines($DocPath, [System.Text.Encoding]::UTF8)

    $inSection = $false
    foreach ($line in $lines) {
        if ($line -match '^###\s+11\.4(\s|$)')  { $inSection = $true;  continue }
        if ($inSection -and $line -match '^###\s+11\.5(\s|$)') { $inSection = $false; break }
        if (-not $inSection) { continue }
        if ($line -notmatch '^\s*\|') { continue }

        $cells = $line.Split('|')
        # A markdown row splits to: '', c1, c2, ..., cN, ''
        if ($cells.Count -lt 6) { continue }
        $c = @()
        for ($k = 1; $k -lt $cells.Count - 1; $k++) { $c += $cells[$k].Trim() }
        if ($c.Count -lt 5) { continue }
        # Header and separator rows.
        if ($c[0] -match '^:?-{2,}') { continue }
        if ($c[0] -eq '#') { continue }

        $loc = $c[1]

        # Property 2: a row without BOTH a grade and a round archives nothing.
        # The main table is 8 columns (grade 6, round 7); the N table is 6
        # (grade 5, round 6).  Read them from the END so both shapes work: the
        # main table ends with an action column, the N table does not.
        $grade = ''; $round = ''
        if ($c.Count -ge 8)     { $grade = $c[5]; $round = $c[6] }
        elseif ($c.Count -eq 6) { $grade = $c[4]; $round = $c[5] }
        else                    { continue }
        if (-not $grade -or -not $round) { continue }

        $files = @()
        foreach ($m in [regex]::Matches($loc, '([A-Za-z_]\w*\.(?:cpp|hpp))')) {
            if (-not ($files -contains $m.Groups[1].Value)) { $files += $m.Groups[1].Value }
        }
        if ($files.Count -eq 0) { continue }

        # Function names: every backticked identifier in the location cell that
        # is not the file name itself.  `setContentSize`, `Layout::invalidate()`,
        # `contentRect()` all reduce to a bare name.
        $funcs = @()
        foreach ($m in [regex]::Matches($loc, '`([^`]+)`')) {
            $tok = $m.Groups[1].Value
            foreach ($idm in [regex]::Matches($tok, '(?<n>[A-Za-z_]\w*)\s*(\(\s*\))?\s*$')) {
                $nm = $idm.Groups['n'].Value
                if ($nm -match '\.(cpp|hpp)$') { continue }
                if ($tok -match '\.(cpp|hpp)') { continue }
                if (-not ($funcs -contains $nm)) { $funcs += $nm }
            }
        }
        if ($funcs.Count -eq 0) { continue }

        $result.Rows++
        foreach ($f in $files) {
            foreach ($fn in $funcs) {
                $result.Keys[($f + '|' + $fn)] = @{ Grade = $grade; Round = $round; Row = $c[0] }
            }
        }
    }

    if ($result.Rows -eq 0) { $result.Error = 'no parseable rows in section 11.4 of ' + $DocPath }
    return $result
}

# ---------------------------------------------------------------------------
# Two extra machine predicates that section 11.4 / 11.9 asked for BY NAME, kept
# here rather than in a second tool because they answer the same question --
# "is the register still telling the truth?" -- and because a check nobody runs
# is not a check.
# ---------------------------------------------------------------------------

# Section 11.4's exemption for Platform.hpp's 21 virtuals rests on ONE
# structural fact: there is no way to install an application's implementation.
# The document says, verbatim, "this grep should go into section 11.9's lint:
# it is a two-line machine predicate, more reliable than a paragraph of
# exemption prose."  The day an install point appears, those 21 enter the table.
function Test-NoPlatformInstallPoint {
    param([string] $Root)
    $hits = New-Object System.Collections.ArrayList
    foreach ($dir in @('include', 'src')) {
        $d = Join-Path $Root $dir
        if (-not (Test-Path -LiteralPath $d)) { continue }
        # Extension tested rather than -Include, for the reason recorded on
        # Get-SourceFiles: -Include does nothing next to -LiteralPath -Recurse,
        # so this loop has been reading every file under include\ and src\,
        # comment-stripping .md and .natvis as if they were C++.  Harmless for
        # THIS predicate -- a wider net cannot make it miss an install point --
        # but a filter that does not filter is not a thing to leave lying about.
        foreach ($f in (Get-ChildItem -LiteralPath $d -Recurse -File |
                        Where-Object { $_.Extension -in @('.hpp', '.cpp', '.h', '.cc') })) {
            $clean = Get-CleanText $f.FullName
            if ($clean -match '\b(setPlatform|installPlatform)\b') {
                [void] $hits.Add($f.FullName.Substring($Root.Length).TrimStart('\'))
            }
        }
    }
    return $hits
}

# EVERY .bat IN THIS TREE MUST STAY PURE ASCII.  This is verify.bat's own rule,
# and it is here because a rule written in a comment is a rule the next tool to
# rewrite the file has never read.
#
# THE MECHANISM, MEASURED RATHER THAN REPEATED.  cmd.exe seeks in a batch file
# by BYTE OFFSET while accounting for what it consumed in CHARACTERS.  The full
# truth table, run on this machine (160 filler lines, one echo, four builds of
# the same file):
#
#     CRLF + UTF-8 multibyte  -> correct
#     CRLF + GBK  multibyte   -> correct
#     LF   + pure ASCII       -> correct
#     LF   + UTF-8 multibyte  -> BROKEN.  The parser resumes mid-line 160 lines
#                                further up and runs the fragment `ine` as a
#                                command, which is exactly the reported symptom.
#
# So it takes BOTH conditions.  verify.bat's note describes it as a property of
# LF; that is half of it, and the half that matters here is the OTHER one.
#
# WHY THIS CHECKS ASCII AND NOT LINE ENDINGS.  All four .bat files in this tree
# are bare-LF today, so the ASCII half is the only thing keeping them working --
# which makes it the half worth enforcing.  Converting them to CRLF was
# considered and rejected on a measurement: core.autocrlf is `true` here and
# there is no .gitattributes, so a CRLF working tree normalises straight back to
# LF in the index.  `git status` calls the file modified and `git diff` shows
# ZERO lines changed -- the conversion cannot be reviewed and cannot be
# committed.  The landable form of that fix is one line of .gitattributes
# (`*.bat text eol=crlf`), which changes what every checkout in the project
# produces and is therefore not a thing a lint should decide by itself.
#
# AND NOTE WHAT THIS CHECK CANNOT DO: it runs FROM verify.bat, so it cannot
# protect verify.bat from a drift that has already happened -- cmd would
# mis-execute the file long before reaching this step.  It protects the NEXT
# run, by failing the gate the moment a non-ASCII byte lands in any .bat.  That
# is why it tests the PRECONDITION and not the symptom.
# ---------------------------------------------------------------------------
# IS THE GATE STILL PLUGGED IN?
#
# The two machine checkers in this tree -- this lint and tools\classify-asan.ps1
# -- are the only things standing between, respectively, an unguarded door and a
# release, and a use-after-free and a release.  Both of them prove themselves
# against fixtures before they speak.  NEITHER OF THEM WAS WATCHING WHETHER THE
# GATE STILL CALLS THEM.
#
# Measured, and it is worse than it sounds: delete `call :lint_doors` from
# verify.bat:55, or `call :classify_asan` from :146, and verify.bat still runs
# all six steps, still prints its six-row summary, and still prints
#
#     [ok] gate is GREEN
#
# because both checkers redden the gate by SETTING A VARIABLE FROM INSIDE a
# subroutine that is no longer called.  A checker that is not invoked fails
# open, silently, and the run that dropped it looks exactly like a clean one.
#
# So this is the third named machine predicate, and it is deliberately the
# stupidest one in the file: strip the batch comments, then look for the two
# calls and the two labels they land on.  A `call` to a label that does not
# exist is not a call either -- cmd prints "cannot find the batch label" and
# carries on to the next line with the rest of the run untouched.
#
# THE COMMENTS ARE STRIPPED FIRST for the same reason Clear-CppNoise exists:
# verify.bat's `rem` blocks are longer than its code and they QUOTE THESE VERY
# LINES ("...prints its own [ ok ] / [FAIL] line", "inside step [1/6]").  A raw
# match would be satisfied by a comment describing the call that somebody just
# deleted, which is the most specific way this check could be useless.
#
# AND THE FILE MUST EXIST.  A missing verify.bat is red, not skipped: "the gate
# is not there" is not a green condition.
function Test-GateStillCallsItsCheckers {
    param([string] $Root)

    $missing = New-Object System.Collections.ArrayList
    $bat = Join-Path $Root 'verify.bat'
    if (-not (Test-Path -LiteralPath $bat)) {
        [void] $missing.Add('verify.bat is not there at all')
        return $missing
    }

    $text = [System.IO.File]::ReadAllText($bat)
    $kept = New-Object System.Collections.ArrayList
    foreach ($line in ($text -split "`r`n|`n|`r")) {
        $t = $line.Trim()
        if ($t -match '^(?i)rem(\s|$)') { continue }
        if ($t -match '^::') { continue }
        [void] $kept.Add($line)
    }
    $code = ($kept -join "`n")

    foreach ($pair in @(
        @{ Label = 'lint_doors';   What = 'the door-coverage lint (this script)' },
        @{ Label = 'classify_asan'; What = 'the ASan report classifier' })) {
        if ($code -notmatch ('(?im)^\s*call\s+:' + $pair.Label + '\s*$')) {
            [void] $missing.Add(('verify.bat never calls :{0} -- {1} is not run' -f $pair.Label, $pair.What))
        }
        elseif ($code -notmatch ('(?im)^\s*:' + $pair.Label + '\s*$')) {
            [void] $missing.Add(('verify.bat calls :{0} but has no such label -- cmd skips it' -f $pair.Label))
        }
    }
    return $missing
}

function Test-BatchFileHygiene {
    param([string] $Root)
    $bad = New-Object System.Collections.ArrayList
    foreach ($f in Get-ChildItem -LiteralPath $Root -File -Filter *.bat) {
        $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
        $lfNoCr   = 0
        $nonAscii = 0
        for ($i = 0; $i -lt $bytes.Length; $i++) {
            if ($bytes[$i] -gt 127) { $nonAscii++ }
            if ($bytes[$i] -eq 10) {
                if ($i -eq 0 -or $bytes[$i - 1] -ne 13) { $lfNoCr++ }
            }
        }
        if ($nonAscii -gt 0) {
            [void] $bad.Add(@{ Name = $f.Name; BareLf = $lfNoCr; NonAscii = $nonAscii })
        }
    }
    return $bad
}

# ---------------------------------------------------------------------------
# The lint proper, as a function that RETURNS its exit code.  The script body at
# the bottom is the only place `exit` appears -- same shape as
# tools\classify-asan.ps1, and for the same reason: the self-test drives this
# in-process.
# ---------------------------------------------------------------------------
function Invoke-LintDoorCoverage {
    param(
        [string] $RepoRoot = '',
        [string] $DocPath = '',
        [string[]] $SrcDirs = @(),
        [string] $IncludeDir = '',
        [int] $MaxList = 40,
        [switch] $Quiet,
        [switch] $Silent
    )

    $script:Emitted = New-Object System.Collections.ArrayList
    $script:Silent  = [bool] $Silent

    try {
        if (-not $RepoRoot) { $RepoRoot = Split-Path -Parent $script:LintDir }
        if (-not $DocPath)  { $DocPath = Join-Path $RepoRoot 'docs\iterations\02-layout-engine.md' }
        if (-not $IncludeDir) { $IncludeDir = Join-Path $RepoRoot 'include\geeyoou' }
        # THE CANDIDATE SIDE HAS THE SAME SCAN ROOT AS THE DECLARATION SIDE, and
        # it did not until the fourth security review found this.  Property 4's
        # second paragraph -- "the scan root is the whole of include\geeyoou, not
        # Widget.hpp" -- was fixed on the DECLARATION side only; the CANDIDATE
        # side was rooted at `src`, and the library's code is not all in `src`.
        # Same hole, second appearance, on the other side of the same script.
        # Measured cost of the omission: AppWindow::setContent and
        # WindowHeader::addTrailingItem, a P2 door each with writes through
        # `this` after it, structurally invisible.
        if ($SrcDirs.Count -eq 0) {
            $SrcDirs = @((Join-Path $RepoRoot 'src'), (Join-Path $RepoRoot 'include'))
        }

        # -- property 4: the P1 name table, generated from the declaration side --
        if (-not (Test-Path -LiteralPath $IncludeDir)) {
            Write-LintLine ('  [lint-doors] include root not found: ' + $IncludeDir)
            return $EXIT_INTERNAL
        }
        $headers = @(Get-ChildItem -LiteralPath $IncludeDir -Recurse -File -Filter *.hpp | ForEach-Object { $_.FullName })
        if ($headers.Count -eq 0) {
            Write-LintLine ('  [lint-doors] no headers under ' + $IncludeDir)
            return $EXIT_INTERNAL
        }
        $virtualsAll = Get-VirtualNames -HeaderPaths $headers
        # The Platform exemption, gated below by Test-NoPlatformInstallPoint.
        $virtuals = Remove-PlatformOnlyNames -Names $virtualsAll
        $exempted = $virtualsAll.Count - $virtuals.Count

        # -- the P2 half of the predicate, also from the document ------------
        $p2 = Read-DoorPrimitivesP2 -DocPath $DocPath
        if ($p2.Error) {
            Write-LintLine ('  [lint-doors] ' + $p2.Error)
            return $EXIT_INTERNAL
        }
        $script:P2Names = $p2.Names

        $matcher = New-DoorMatcher -VirtualNames $virtuals

        # -- the allowlist --------------------------------------------------
        $allow = Read-DoorAllowlist -DocPath $DocPath
        if ($allow.Error) {
            Write-LintLine ('  [lint-doors] ' + $allow.Error)
            return $EXIT_INTERNAL
        }

        # -- the candidate set ----------------------------------------------
        $candidates = New-Object System.Collections.ArrayList
        $guarded    = 0
        $scanned    = 0
        $broken     = New-Object System.Collections.ArrayList

        foreach ($dir in $SrcDirs) {
            if (-not (Test-Path -LiteralPath $dir)) { continue }
            foreach ($f in (Get-SourceFiles -Dir $dir)) {
                $scanned++
                $clean = Get-CleanText $f.FullName
                $idx   = New-LineIndex $clean
                $leaf  = $f.Name

                foreach ($fn in (Split-CppFunctions -Clean $clean)) {
                    if ($fn.Unbalanced) {
                        [void] $broken.Add(($leaf + ' :: ' + $fn.Name))
                        continue
                    }
                    $body = $clean.Substring($fn.BodyStart, $fn.BodyEnd - $fn.BodyStart)
                    $doors = @(Find-Doors -Body $body -Matcher $matcher)
                    if ($doors.Count -eq 0) { continue }

                    $live = @($doors | Where-Object { Test-CodeFollowsDoor -Body $body -DoorOffset $_.Offset })
                    if ($live.Count -eq 0) { continue }

                    if ($body -match $script:CursorGuardPattern) { $guarded++; continue }

                    # NOT $home: that is a read-only automatic variable in
                    # PowerShell and assigning it throws, which this script then
                    # catches and turns into exit 3 -- a red gate for a reason
                    # that has nothing to do with doors.
                    $key = $leaf + '|' + $fn.Name
                    $homeRow = $null
                    if ($allow.Keys.ContainsKey($key)) { $homeRow = $allow.Keys[$key] }

                    $first = $live[0]
                    [void] $candidates.Add(@{
                        File = $leaf
                        Func = $fn.Name
                        Qualified = $fn.Qualified
                        Line = (Get-LineOf -LineStarts $idx -Offset ($fn.BodyStart + $first.Offset))
                        Kinds = (($live | ForEach-Object { $_.Kind }) | Sort-Object -Unique) -join '/'
                        Doors = $live.Count
                        Sample = ($first.Kind + ' ' + $first.Name)
                        Home = $homeRow
                    })
                }
            }
        }

        $unarchived = @($candidates | Where-Object { $null -eq $_.Home })
        $archived   = @($candidates | Where-Object { $null -ne $_.Home })

        # -- the two named machine predicates ---------------------------------
        $platformHits = @(Test-NoPlatformInstallPoint -Root $RepoRoot)
        $batBad       = @(Test-BatchFileHygiene -Root $RepoRoot)
        $gateUnwired  = @(Test-GateStillCallsItsCheckers -Root $RepoRoot)

        # -- report -----------------------------------------------------------
        # The P2 COUNT is printed, not just the archived-row count, and the
        # reason is the direction each one can drift in.  Losing an allowlist
        # row makes the gate redder; losing a P2 primitive makes it GREENER, by
        # deleting a class of candidate, and nothing else in this script can see
        # that happen.  A number in the gate log is what makes the shrink show
        # up in a diff of two runs.
        Write-LintLine ('  [lint-doors] {0} virtual name(s) from {1} header(s) ({2} Platform-only, exempt) + {3} P2 primitive(s) from section 11.4; {4} source file(s); section 11.4 archived {5} row(s)' -f `
            $virtuals.Count, $headers.Count, $exempted, $script:P2Names.Count, $scanned, $allow.Rows)
        Write-LintLine ('  [lint-doors] candidates: {0} guarded (DeathWatch), {1} archived, {2} UNARCHIVED' -f `
            $guarded, $archived.Count, $unarchived.Count)

        $red = $false

        if ($broken.Count -gt 0) {
            $red = $true
            Write-LintLine '  [lint-doors] FAIL: function bodies this script could not delimit (fail closed):'
            foreach ($b in $broken) { Write-LintLine ('      ' + $b) }
        }

        if ($unarchived.Count -gt 0) {
            $red = $true
            Write-LintLine '  [lint-doors] FAIL: candidates with no home. Guard the frame, or register it'
            Write-LintLine '               in section 11.4 with a reason, a grade and a round:'
            $shown = 0
            foreach ($u in ($unarchived | Sort-Object File, Func)) {
                $shown++
                if ($shown -gt $MaxList) { continue }
                Write-LintLine ('      {0}::{1}  line {2}  [{3}, {4} door(s), first: {5}]' -f `
                    $u.File, $u.Func, $u.Line, $u.Kinds, $u.Doors, $u.Sample)
            }
            if ($unarchived.Count -gt $MaxList) {
                Write-LintLine ('      ... and {0} more.' -f ($unarchived.Count - $MaxList))
            }
        }

        if ($platformHits.Count -gt 0) {
            $red = $true
            Write-LintLine '  [lint-doors] FAIL: an implementation install point for Platform now exists, so'
            Write-LintLine '               section 11.4 s exemption for Platform.hpp s 21 virtuals has lapsed.'
            Write-LintLine '               Put them in the table, graded one by one:'
            foreach ($h in $platformHits) { Write-LintLine ('      ' + $h) }
        }

        if ($gateUnwired.Count -gt 0) {
            $red = $true
            Write-LintLine '  [lint-doors] FAIL: the gate no longer invokes one of its own checkers, so that'
            Write-LintLine '               checker fails OPEN -- verify.bat runs all six steps and prints'
            Write-LintLine '               "gate is GREEN" with nothing watching. Put the call back:'
            foreach ($g in $gateUnwired) { Write-LintLine ('      ' + $g) }
        }

        if ($batBad.Count -gt 0) {
            $red = $true
            Write-LintLine '  [lint-doors] FAIL: a batch file is no longer pure ASCII. cmd.exe mis-executes a'
            Write-LintLine '               batch file that has BOTH bare-LF endings AND multi-byte characters,'
            Write-LintLine '               and every .bat here is bare-LF, so ASCII is what keeps them working.'
            Write-LintLine '               Move the text into a .ps1, as tools\test-classify-asan.ps1 does:'
            foreach ($b in $batBad) {
                Write-LintLine ('      {0}: {1} non-ASCII byte(s), {2} bare-LF line(s)' -f $b.Name, $b.NonAscii, $b.BareLf)
            }
        }

        if (-not $Quiet -and $archived.Count -gt 0) {
            Write-LintLine '  [lint-doors] archived candidates (section 11.4 has a row for each):'
            foreach ($a in ($archived | Sort-Object File, Func)) {
                Write-LintLine ('      {0}::{1}  line {2}  [{3}]  -> row {4}, {5}, {6}' -f `
                    $a.File, $a.Func, $a.Line, $a.Kinds, $a.Home.Row, $a.Home.Grade, $a.Home.Round)
            }
        }

        if ($red) { return $EXIT_UNCOVERED }
        return $EXIT_COVERED
    }
    catch {
        Write-LintLine ('  [lint-doors] INTERNAL ERROR, failing closed: ' + $_.Exception.Message)
        Write-LintLine ('  [lint-doors] at: ' + $_.InvocationInfo.PositionMessage)
        return $EXIT_INTERNAL
    }
}

# ---------------------------------------------------------------------------
# Script body.  The only `exit` in the file.
# ---------------------------------------------------------------------------
if ($DefineOnly) { return }

if ($GateWiringOnly) {
    $root = $RepoRoot
    if (-not $root) { $root = Split-Path -Parent $script:LintDir }
    $bad = @(Test-GateStillCallsItsCheckers -Root $root)
    if ($bad.Count -eq 0) { exit $EXIT_COVERED }
    foreach ($b in $bad) { [Console]::Out.WriteLine('  [gate-wiring] ' + $b) }
    exit $EXIT_UNCOVERED
}

exit (Invoke-LintDoorCoverage -RepoRoot $RepoRoot -DocPath $DocPath -MaxList $MaxList -Quiet:$Quiet)
